### ISSUE TITLE
AMQP connection issue

### ISSUE THREAD

**Issue by higherkuo** [Azure-Samples/web-apps-node-iot-hub-data-visualization#2]
Hi,
I'm following the [documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-live-data-visualization-in-web-apps) here. However, it only works about 10% of the time. Most of the time the page just receives nothing.

I dig a little bit into the log file. The error message from Azure web-app is following:
```
 Application has thrown an uncaught exception and is terminated:
TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (D:\home\site\wwwroot\node_modules\amqp10\lib\frames.js:54:9)
    at Connection.sendFrame (D:\home\site\wwwroot\node_modules\amqp10\lib\connection.js:333:10)
    at ReceiverLink.Link.attach (D:\home\site\wwwroot\node_modules\amqp10\lib\link.js:108:27)
    at ReceiverLink.Link._attemptReattach (D:\home\site\wwwroot\node_modules\amqp10\lib\link.js:237:8)
    at Timeout._onTimeout (D:\home\site\wwwroot\node_modules\amqp10\lib\link.js:225:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
The initial google search indicates the problem is coming from AMQP connection. But I couldn't find a working solution to this problem.

Any suggestions?

Thanks,

**Comment by yuwzho** [comment]
Hi @higherkuo
Yes, I find the same issue as you. I solve this problem by upgrading the `azure-event-hub` package version to `0.0.8`. Also there are some change bewteen the two versions. You can checkout the latest sample code to run the web app.
Thanks
