### ISSUE TITLE
Cannot deploy locally

### ISSUE THREAD

**Issue by suleymanov** [Azure-Samples/web-apps-node-iot-hub-data-visualization#9]
I followed instructions in README:
-- set Azure.IoT.IoTHub.ConnectionString=<your connection string>
-- set Azure.IoT.IoTHub.ConsumerGroup=<your consumer group name>

```npm install```
```npm start```

and I get error:

    > webapp@0.0.0 start /Users/railsuleymanov/Documents/azure_projects/repos/examples/web-apps-node-iot-hub-data-visualization
    > node server.js

    /Users/railsuleymanov/Documents/azure_projects/repos/examples/web-apps-node-iot-hub-data-visualization/node_modules/azure-event-hubs/lib/client.js:87
        throw new ArgumentError('Missing argument connectionString');
        ^
    ArgumentError: Missing argument connectionString
        at Function.EventHubClient.fromConnectionString (/Users/railsuleymanov/Documents/azure_projects/repos/examples/web-apps-node-iot-hub-data-visualization/node_modules/azure-event-hubs/lib/client.js:87:11)
        at new IoTHubReaderClient (/Users/railsuleymanov/Documents/azure_projects/repos/examples/web-apps-node-iot-hub-data-visualization/IoTHub/iot-hub.js:44:38)
    at Object.<anonymous> (/Users/railsuleymanov/Documents/azure_projects/repos/examples/web-apps-node-iot-hub-data-visualization/server.js:32:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! webapp@0.0.0 start: `node server.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the webapp@0.0.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/railsuleymanov/.npm/_logs/2018-02-07T12_00_21_785Z-debug.log

**Comment by dolveravogar** [comment]
Are you using **""** in the _ConnectionString_? I type the connection string without **""** after the **=** and then I stop getting that message. But now I go in my web browser to _LocalHost:3000_ and it is no chart!!!

**Comment by SLdragon** [comment]
@suleymanov seems like you do not provide the correct connection string

**Comment by SLdragon** [comment]
@dolveravogar, maybe you do not change the wss:// to ws://, please refer the latest readme to fix this issue
